# hydra.job.chdir: false

headless: true
use_local_usd: false

sim: ${task.sim}
env: ${task.env}

model_dir: null

total_frames: 9000_000_000 #1000_000_000
max_iters: -1
eval_interval: -1
save_interval: 100
seed: 0

viewer:
  resolution: [960, 720]
  # front
  # eye: [0., 2.0, 10.0]
  # lookat: [0., 0., 1.0]
  eye: [0., 2.0, 2.5]
  lookat: [0., 0., 1.0]

wandb:
  group: ${oc.select:..task.name}
  run_name: track_actor_addtime_seed0
  # run_name: debug
  job_type: train
  entity: chenjy
  project: sim2real_RAL
  # mode: disabled
  mode: online # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  - task: Track
  # - task: Hover
  - algo: mappo
  - _self_
