# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

# model_dir: /home/zanghongzhi/isaac_ws/OmniDrones/scripts/outputs/Track_v_range2to2_2_smooth10/08-12_20-54/wandb/run-20240812_205453-8k7didxj/files/checkpoint_final.pt
model_dir: null

total_frames: 3000_000_000 #1000_000_000
max_iters: -1
eval_interval: -1
save_interval: 100
seed: 0

viewer:
  resolution: [960, 720]
  # # front
  # eye: [0., -0.005, 6.]
  # lookat: [0., 0., 1.]
  eye: [0., 2.0, 2.5]
  lookat: [0., 0., 1.0]

wandb:
  group: ${oc.select:..task.name}
  # run_name: Track_v_range0_5to1_2_smooth10
  # run_name: Rotate_v_range2to2_2_smooth10_eval2
  run_name: debug
  job_type: train
  entity: chenjy
  project: simpleflight
  mode: disabled
  # mode: online # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  - task: Track
  # - task: Hover
  # - task: Rotate
  # - task: MultiGoto
  # - task: Goto_static
  # - task: Exchange
  - algo: mappo
  - _self_
