# hydra.job.chdir: false

headless: true

sim: ${task.sim}
env: ${task.env}

# model_dir: /home/zanghongzhi/isaac_ws/OmniDrones/scripts/outputs/Track_slow_lr0/08-18_21-27/wandb/run-20240818_212757-b3ubojde/files/checkpoint_1494482944.pt
# model_dir: /home/chenjy/OmniDrones/scripts/outputs/Hover_quat_rotation_matrix_smooth0/10-21_22-12/wandb/run-20241021_221236-1oj2iglv/files/checkpoint_final.pt
model_dir: null

total_frames: 9000_000_000 #1000_000_000
max_iters: -1
eval_interval: -1
save_interval: 100
seed: 0

viewer:
  resolution: [960, 720]
  # # front
  # eye: [0., -0.005, 6.]
  # lookat: [0., 0., 1.]
  eye: [0., 2.0, 2.5]
  lookat: [0., 0., 1.0]

wandb:
  group: ${oc.select:..task.name}
  # run_name: Hover_rpos_quat_linearv_rotation_wotime
  run_name: Track_mixed_norm_smooth1
  job_type: train
  entity: chenjy
  project: simpleflight
  # mode: disabled
  mode: online # set to 'disabled' when debugging locally, online
  run_id: 
  monitor_gym: True
  tags: 

defaults:
  - task: Track
  # - task: Hover
  - algo: mappo
  - _self_
